### ISSUE TITLE
Add recursive search feature

### ISSUE THREAD

**Issue by rolandomunoz** [jeanphilippegoldman/plugin_filetools#11]
Should I add the recursive search feature to the `Resample files`and `Get duration` commands?

**Comment by jeanphilippegoldman** [comment]
good idea. could be nice. maybe we could put all the checkextension and create file list thing in a unique proc (open_file3 lines 38 to 56)

**Comment by rolandomunoz** [comment]
Done! Please, take a look to [restrict_extensions](https://github.com/jeanphilippegoldman/plugin_filetools/tree/restrict_extensions) branch. I have taken a different approach to valid extensions. 
Once `Create Strings as file list` is run, we remove all those files that do not match the valid extensions in the same object. Then, we compute the procedures. From my point of view, this make the code a little clearer and easy to maintain in the future.

There is one last thing, at this moment, the scripts don't report those files that cannot be opened. I would reactivate this behavior later.

**Comment by rolandomunoz** [comment]
I  close this issue. I merged the changes to the main branch.
