### ISSUE TITLE
Get durations from interval tiers

### ISSUE THREAD

**Issue by rolandomunoz** [jeanphilippegoldman/plugin_filetools#12]
I have thought that it would be great if we could get the duration time from interval tiers. We could select intervals according to their contents and make a time report.

I have scheme this idea a put it on the [dev branch](https://github.com/jeanphilippegoldman/plugin_filetools/tree/dev). Please, let mi know if this idea fits with the plug-in propose?

**Comment by jeanphilippegoldman** [comment]
hum i have a similar plugin named TextGrid tools with all this already (and many other tools ~30)
I have to tidy this and put it online.  We can do it together but our main goal is easyalign, remember ? ;-)

**Comment by rolandomunoz** [comment]
Wow! You have many plug-ins! Ok, I close this issue.
