### ISSUE TITLE
Traverse all files in a root folder

### ISSUE THREAD

**Issue by rolandomunoz** [jeanphilippegoldman/plugin_filetools#4]
I have created script (under GNU GPL) which traverse all files in a root folder. I think it would be useful to use add my script to your plug-in. Do you mind if I make some changes in that way?

**Comment by jeanphilippegoldman** [comment]
you mean subfolders, and recursively ? i have such one level option in open_files.

but if you can find a way to include it more generically as a procedure to be able to include it in other scripts, please go ahead.

point me to your script first please.

**Comment by rolandomunoz** [comment]
Yes. My procedure is n level.

Go to list_recursive_path.proc in [here](https://github.com/rolandomunoz/plugin_finder/tree/master/procedures). The Finder use this procedure.

Please, let me know if you need something.

**Comment by jeanphilippegoldman** [comment]
yes i had found it. lets not open too many issue discussion if they are related.
