### ISSUE TITLE
open files crashes if  a subfolder has a dot AND recursive path is on

### ISSUE THREAD

**Issue by jeanphilippegoldman** [jeanphilippegoldman/plugin_filetools#9]
open_files crashes on Windows if a subfolder has a dot AND recursive path is on

eg. C:\Users\goldman\Documents\corpus.new\

**Comment by rolandomunoz** [comment]
Oh... Thank you. I'll debug the `list_recursive_path.proc`

**Comment by rolandomunoz** [comment]
@jeanphilippegoldman Can you send me a picture of the crash?

I have run a little test on Windows and couldn't find the error.
![image](https://user-images.githubusercontent.com/18198623/41749539-96b00668-757c-11e8-83fb-fd062b934fed.png)

**Comment by jeanphilippegoldman** [comment]
![image](https://user-images.githubusercontent.com/14802091/41778137-040f10bc-762e-11e8-9a7c-88976dd31ff0.png)

**Comment by rolandomunoz** [comment]
Ohh... I'm not sure about this.Which version of Praat do you have? "~" syntax was introduced in later versions (>= 6.0.32)

**Comment by jeanphilippegoldman** [comment]
right. version pb. sorry about that .solved
